### ISSUE TITLE
timechart: do better downsampling

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle-viz#6]
The original idea was to change -display.dataDensity to -downsample and make it a boolean, to simplify the options. 

However, the new thinking is that we should make the default density denser, and use up all available pixels, before we force downsampling.

Unclear if we still would need an option to let the user control it. If we do, make it `-downsample <true|false>`

And update the docs.

**Comment by go-oleg** [comment]
There was some discussion as to whether we should do 1 or 2 pixels per point, here are screenshots for the two:

1 pixel per point
![image](https://cloud.githubusercontent.com/assets/3344137/13266638/df030c2c-da2d-11e5-8953-529891bd402a.png)

2 pixels per point
![image](https://cloud.githubusercontent.com/assets/3344137/13266597/af01fd94-da2d-11e5-940d-4f812d7e851a.png)

I don't think 1 pixel per point provides any value and looks significantly more cluttered than 2, so going with 2.

**Comment by dmehra** [comment]
+1 to 2 per point

**Comment by demmer** [comment]
I agree

On Tue, Feb 23, 2016 at 1:39 PM, Daria Mehra notifications@github.com
wrote:

> +1 to 2 per point
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/juttle/juttle-viz/issues/6#issuecomment-187925410.

## 

Michael Demmer
Jut - CTO / VP Engineering
demmer@jut.io
